language: python
  - "2.7"
  - "3.7"

services:
  - docker

before_install:
  - docker run -d -p 4000:80 dongahn/friendlyhello:v0.0.1
  - docker container ls

install:
  - pip install --user pycotap

script:
  - make check
  - curl localhost:4000

